language: php

php:
  - 5.5
  - 5.4
  - 5.3
  - 5.2

before_install:
  - sudo apt-get update > /dev/null

install:
  - sudo apt-get install -y --force-yes make php5-dev php-pear libmagic-dev 
  - pecl install fileinfo
  - echo "extension=fileinfo.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - sudo apachectl restart



script: make
