language: php

php:
  - 5.5
  - 5.4
  - 5.3
  - 5.2

before_install:
  - sudo apt-get update > /dev/null

install:
  - sudo apt-get install -y --force-yes make php5-dev php-pear libmagic-dev 
	- pecl install fileinfo
 	- sudo echo "extension=fileinfo.so" > /etc/php5/fileinfo.ini
	- sudo apachectl restart



script: make
